### PR TITLE
Some fixes for dynamic selectedDates

### PR DESCRIPTION
**Pull request by murphyalexandre**
Fixes include:

* Updating selectedDates when using dynamic data.
* Showing update when selectedDates not on the same month.
* Fixed a problem with indexOf of undefined.

### CODE REVIEW

**Comment by spongessuck** [comment]
Thanks for the PR, @murphyalexandre.

Could you give a test case where your changes would be useful? I'm not getting what you mean by 'using dynamic data' for selectedDates.

**Comment by murphyalexandre** [comment]
I've created a plunk using $timeout to simulate an API call : [http://plnkr.co/edit/16IuKCEOGkNbm3mQRoq6?p=preview](http://plnkr.co/edit/16IuKCEOGkNbm3mQRoq6?p=preview).

As you can see, when the selectedDates changes, it shows up in the well, but the calendar doesn't update. When you remove the date from the well, all the other actions afterwards aren't really working as intended.

Maybe my fix doesn't address those issues, but it's essentially the way I'm using your lib (which is really nice btw).

**Comment by spongessuck** [comment]
I've made a minor change to my original script that I think will make everything work for you. Let me know if it doesn't solve the issues you had.

You can find it on this fork of your Plunk:

http://plnkr.co/edit/6wgblKclSpk5ImOfxf3I?p=preview

**Comment by murphyalexandre** [comment]
This partially works for me. Since you don't check newVal for undefined or null, it gets set and sends the update to the decorator and then throws errors while trying to do indexOf on null object.

**Comment by spongessuck** [comment]
OK this should do it:

http://plnkr.co/edit/6wgblKclSpk5ImOfxf3I?p=preview

**Comment by murphyalexandre** [comment]
Bingo! Thanks!

**Comment by spongessuck** [comment]
No problem. Glad you find the module useful!

**Pull request closed without merging**
